#!/bin/bash
# Load all variables and keep them in a readable format.
function loadVariables {
	for var in "$@"
	do
		export "$var"
	done
}

# Variables
loadVariables \
ARCH=arm64 \
CROSS_COMPILE=arm-linux-androideabi- \
DEFCONFIG=exynos7570-on5xelte_mea_defconfig \
MAKEFLAGS="O=out -j$(nproc --all) LLVM=1" \
PATH="$PWD/build/build-tools/clang-r383902/bin:$PWD/build/build-tools/aarch64-linux-android-4.9/bin:$PWD/build/build-tools:$PATH"
