#!/bin/bash
# Load all variables and keep them in a readable format.
function loadVariables {
	for var in "$@"
	do
		export "$var"
	done
}

# Variables
loadVariables \
ARCH=arm64 \
CROSS_COMPILE=aarch64-linux-gnu- \
DEFCONFIG=X00P_defconfig \
MAKEFLAGS="O=out -j$(nproc --all) LLVM=1" \
PATH="$PWD/build/build-tools/proton-clang/bin:$PATH"
